# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.1 on 2017-06-05 14:34
=======
# Generated by Django 1.11.1 on 2017-05-29 18:58
>>>>>>> 8203410f39f5bafc0ce5ee4176a071e801d8781c
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodio', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=50)),
=======
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
>>>>>>> 8203410f39f5bafc0ce5ee4176a071e801d8781c
            ],
        ),
    ]
