# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episodio',
            new_name='episode',
        ),
    ]
