# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
