# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0002_auto_20170605_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='download',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
