# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0002_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='abbrev',
            field=models.CharField(default='cobre', max_length=6),
            preserve_default=False,
        ),
    ]
