# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0002_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
