# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0003_episode_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
