# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0004_auto_20170605_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microfonia.Serie'),
        ),
    ]
