# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfonia', '0005_auto_20170605_2057'),
        ('microfonia', '0003_episode_episode_season'),
    ]

    operations = [
    ]
